### ISSUE TITLE
Widget öffnet beim Berühren die Scriptable App, nicht die Telekom Website

### ISSUE THREAD

**Issue by Wombat2018** [marcjulianschwarz/telekom-data-usage-widget#2]
Hallo,

ich finde das Widget klasse, allerdings öffnet das Widget bei Berührung nicht automatisch die Telekom Website, sondern die Scriptable App.
Was mache ich falsch?

**Comment by marcjulianschwarz** [comment]
Hallo @Wombat2018,

danke für das Feedback.

Scheinbar ist da was schief gelaufen, werde mir das nochmal anschauen und Bescheid geben wenn es gefixt wurde.

**Comment by t0mi** [comment]
![image](https://user-images.githubusercontent.com/51470532/170688888-fe747809-9dbb-479c-8003-71291104cadd.png)

Hast du das auch richtig eingestellt? Bei mir funktioniert es nämlich problemlos. iPhone 13 Pro | iOS 15.6 Developer Beta

**Comment by marcjulianschwarz** [comment]
Danke @t0mi fürs Testen. Stimmt, es muss natürlich beim ersten Setup `Open URL` ausgewählt werden.

**Comment by Wombat2018** [comment]
Achso, und dann trägt man manuell unter URL pass.telekom.de ein? So ist das gemeint?

**Comment by marcjulianschwarz** [comment]
Ja ich denke das war so gemeint. Werde das noch ins README schreiben. Habe das wohl damals vergessen.

Edit: Oder auch nicht, ich erinnere mich daran, dass ich eigentlich das hier verwendet habe: https://docs.scriptable.app/listwidget/#url

Scheinbar ist das irgendwie verloren gegangen. Wenn ich das wieder hinzufügen sollte es auch ohne Setup klappen.

**Comment by marcjulianschwarz** [comment]
Mit dem Commit 0ed25c7bcc29de49d60e0660b42dd1593e055458 sollte es jetzt auch ohne Setup wieder funktionieren.

Die neueste Version gibt es auch auf meiner [Webseite](https://www.marc-julian.de/projects.html) zum herunterladen.
